"""Print the header ``make lock`` writes at the top of ``constraints.txt``.

The declarations are recorded there because the pins alone cannot witness a
*widened* bound: loosen a range and every pin still satisfies it, so a guard
that only checks membership stays green while the contract quietly changes.
Listing what the lock was generated from turns that into a diff a reader sees
and a test can fail on.

Run from the repository root; the caller passes the platform the resolution was
taken for, which is part of what the file means.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path


def declaration_lines(pyproject: Path) -> list[str]:
    """The raw requirement strings, exactly as written in the file.

    Raw rather than parsed: the test that compares the two reads this same
    function, and a normalised form would hide a rewrite that changed nothing
    while showing one that did.
    """
    project = tomllib.loads(pyproject.read_text())["project"]
    lines = list(project["dependencies"])
    for extra in project["optional-dependencies"].values():
        lines.extend(extra)
    return sorted(set(lines))


def header(pyproject: Path, platform: str) -> str:
    out = [
        '# Generated by "make lock" — do not edit by hand.',
        "#",
        f"# The exact resolution the two Python images and CI install, for {platform}.",
        "# Regenerate after changing any dependency in pyproject.toml and commit both",
        "# files together: a test fails when they disagree.",
        "#",
        "# Generated from these declarations:",
    ]
    out += [f"#   {line}" for line in declaration_lines(pyproject)]
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    platform = sys.argv[1] if len(sys.argv) > 1 else "an unrecorded platform"
    print(header(Path("pyproject.toml"), platform))
